var ljApp= new Vue({
    el:"#ljApp",
     data:{
            msg:"菜单部分",
            fg:true,
            li_title:"入门指南",
            li_part1:"平台简介",
            li_part2:"平台操作流程",
            li_art1:"中控",
            li_art2:"登录注册实名认证",
            menuList:[
                {"id":1,"name":"入门指南"},
                {"id":2,"name":"应用创建指南"},
                {"id":3,"name":"服务使用指南"},
                {"id":4,"name":"常见问题"}
            ]
        },
        components:{
            "menu-list":{
                template:'<li :id="id" @click="fun(id)">{{name}}</li>',
                props:['name','id'],
                methods:{
                    fun:function(obj){
                        console.log(obj)
                    }
                }
            }
        }
    })  